name = "websites_checker"
version = "1.0.0"
licences = ["MIT"]
target = "erlang"
gleam = ">= 1.4.1"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"
glaml = ">= 1.0.1 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
